name: Apply Terraform

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        required: true
        type: string
      region:
        required: true
        type: string
      versioning:
        description: "Enable Versioning"
        required: true
        type: boolean

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Assume AWS Role using OIDC
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::730335384723:role/interns_backstage_io
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}
          TF_VAR_bucket_name: ${{ github.event.inputs.bucket_name }}
          TF_VAR_region: ${{ github.event.inputs.region }}
          TF_VAR_versioning: ${{ github.event.inputs.versioning }}
          
